# Generated by Django 4.2.6 on 2023-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizemodel',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thicknessmodel',
            name='thickness',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
