# Generated by Django 4.2.6 on 2023-11-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sizemodel_size_alter_thicknessmodel_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categorymodel'),
        ),
    ]
