# Generated by Django 4.2.6 on 2023-11-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reviewsmodel_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='color_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('hide', 'Hide')], default='pending', max_length=20),
        ),
    ]
