# Generated by Django 4.2.6 on 2023-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactmodel_alter_colormodel_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='modified_at',
        ),
    ]
