# Generated by Django 4.2.6 on 2023-11-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_wishlistmodel_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.variantmodel'),
        ),
    ]
