# Generated by Django 4.2.6 on 2023-11-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_billingaddressmodel_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='product',
        ),
    ]
