# Generated by Django 4.2.6 on 2023-11-11 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_orderitemmodel_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governoratesmodel',
            old_name='governorates',
            new_name='governorates_name',
        ),
        migrations.AddField(
            model_name='governoratesmodel',
            name='governorates_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
