# Generated by Django 4.2.6 on 2023-11-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_governorates_governoratesmodel_governorates_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
