# Generated by Django 4.2.6 on 2023-11-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ordermodel_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsmodel',
            old_name='order_status',
            new_name='review_status',
        ),
    ]
