# Generated by Django 4.2.6 on 2023-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_ordermodel_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
