# Generated by Django 4.2.6 on 2023-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ordermodel_governorates_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
