# Generated by Django 4.2.6 on 2023-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_orderitemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='billing_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
