# Generated by Django 4.2.6 on 2023-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ordermodel_billing_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='governorates_amount',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='governorates_name',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_apartment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_governorates_amount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_governorates_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_house_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_past_code_zip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_phone_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_town',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_apartment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_house_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_post_code_zip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_town',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
