# Generated by Django 4.2.6 on 2023-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_categorymodel_category_image_alter_reviewsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
