# Generated by Django 4.2.6 on 2023-12-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variantmodel',
            name='thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.thicknessmodel'),
        ),
        migrations.AddField(
            model_name='variantmodel',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategorymodel'),
        ),
    ]
