# Generated by Django 4.2.6 on 2023-12-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_subcategorymodel_alter_variantmodel_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Ready for Dispatch', 'Ready for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='variantmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategorymodel'),
        ),
    ]
