# Generated by Django 4.2.6 on 2023-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_orderitemmodel_variant_orderitemmodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
