# Generated by Django 4.2.6 on 2023-12-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_orderitemmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colormodel',
            name='color_code',
        ),
    ]
