# Generated by Django 4.2.6 on 2023-12-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_colormodel_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='txn_id',
            new_name='txn_order_id',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='txn_pay_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variantmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategorymodel'),
        ),
    ]
